first-iteration
dmiheev/go-first-floor-sprint-five pull request #1
Opened 2024-11-22 08:26 UTC by dmiheev

2024-11-23 08:23 UTC, just-musha requested changes
Привет! Непохая работа, основное ок, используешь нужные константы, все ок по стилю. Но есть что поправить - trainingInfo для swimming, проверки на 0 в нужных местах и формулу проверить. И будет принято

2024-11-23 08:23 UTC, just-musha commented on .idea/.gitignore
Директорию .idea не нужно добавлять в ПР. Лучшее ее сразу прописывать в .gitignore файле в корне проекте. Сейчас не крит, учти в будущих работах

2024-11-23 08:23 UTC, just-musha commented on main.go
> +	return t.distance() / t.Duration.Hours()
Перед делением нужна проверка знаменателя на 0, как было в 4 спринте. Давай добавим, и в других местах ниже по коду, где это необходимо

2024-11-23 08:23 UTC, just-musha commented on main.go
> +	return s.Training.TrainingInfo()
В случае с swimming, скорость вычисляется в конкретной реализации meanSpeed для Swimming. Здесь тебе нужно явно вызвать метод s.meanSpeed() для Swimming и проставить значение в структуре InfoMesssage

2024-11-23 08:23 UTC, just-musha commented on main.go
> +	return (CaloriesWeightMultiplier*w.Weight + (math.Pow(KmHInMsec*w.meanSpeed(), 2)/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours
Тут стоит проверить формулу, должно получиться 947.82

2024-11-23 08:40 UTC, dmiheev commented on .idea/.gitignore
готово

2024-11-23 08:45 UTC, dmiheev commented on main.go
> +	return t.distance() / t.Duration.Hours()
готово

2024-11-23 08:49 UTC, dmiheev commented on main.go
> +	return s.Training.TrainingInfo()
готово

2024-11-23 09:11 UTC, dmiheev commented on main.go
> +	return (CaloriesWeightMultiplier*w.Weight + (math.Pow(KmHInMsec*w.meanSpeed(), 2)/w.Height/CmInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours
готово

2024-11-24 09:17 UTC, just-musha approved these changes
Все верно! Отлично что исправлено все, даже не обязательное. Надеюсь что было полезно. Принято!

2024-11-24 09:17 UTC, just-musha commented on main.go
> +	return (CaloriesWeightMultiplier*w.Weight + (math.Pow(meanSpeedInMsec, 2)/heightInM)*CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Minutes()
:+1: хорошо что используешь встроенный метод для приведения к минутам, всегда лучше использовать готовое

2024-11-24 09:17 UTC, just-musha commented on main.go
> +	if r.Duration == 0 {
Тут можно не проверять, тк нет деления на эту переменную.

2024-11-24 09:27 UTC, merged